name: Go
on: [push]
jobs:

  linux:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: setup
      run: curl -L https://git.io/fjaxx | repo=ysmood/kit bin=godev sh
 
    - name: test
      run: godev -l

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
